### ISSUE TITLE
Cloud9 installation error

### ISSUE THREAD

**Issue by Samuelseggs** [wrxck/mattata#20]
E: Unable to locate package lua5.3
E: Couldn't find any package by regex 'lua5.3'
E: Unable to locate package liblua5.3-dev
E: Couldn't find any package by regex 'liblua5.3-dev'
Successfully installed redis-dump-0.3.5
1 gem installed
fatal: destination path 'luarocks' already exists and is not an empty directory.
$PATH interpreter not found in 
You may want to use the flags --with-lua, --with-lua-bin and/or --lua-suffix. See --help.

configure failed.

Makefile:2: config.unix: No such file or directory
make: *** No rule to make target `config.unix'.  Stop.
Makefile:2: config.unix: No such file or directory
make: *** No rule to make target `config.unix'.  Stop.
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
Finished. Use './launch' to start mattata. Be sure to set your bot token in configuration.example.lua, and then rename it to configuration.lua!

**Comment by joostlek** [comment]
curl -R -O http://www.lua.org/ftp/lua-5.3.4.tar.gz
tar zxf lua-5.3.4.tar.gz
cd lua-5.3.4
make linux test
make install

Try running this first, then try installing again

**Comment by Samuelseggs** [comment]
Any other dependencies to install?
sudo apt-get install libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev libevent-dev make unzip git redis-server g++ libjansson-dev libpython-dev expat libexpat1-dev 

should i install ?

**Comment by Samuelseggs** [comment]
still got error 

Reading package lists... Done
W: Size of file /var/lib/apt/lists/toolbelt.heroku.com_ubuntu_._Packages.gz is not what the server reported 721 725
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'fortune-mod' instead of 'fortune'
E: Unable to locate package lua5.3
E: Couldn't find any package by regex 'lua5.3'
E: Unable to locate package liblua5.3-dev
E: Couldn't find any package by regex 'liblua5.3-dev'
Fetching: drydock-0.6.9.gem (100%)
Successfully installed drydock-0.6.9
Fetching: uri-redis-0.4.2.gem (100%)
Successfully installed uri-redis-0.4.2
Fetching: redis-3.3.3.gem (100%)
Successfully installed redis-3.3.3
Fetching: yajl-ruby-1.3.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed yajl-ruby-1.3.0
Fetching: redis-dump-0.3.5.gem (100%)
Successfully installed redis-dump-0.3.5
5 gems installed
Cloning into 'luarocks'...
remote: Counting objects: 9643, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 9643 (delta 0), reused 0 (delta 0), pack-reused 9638
Receiving objects: 100% (9643/9643), 22.95 MiB | 14.25 MiB/s, done.
Resolving deltas: 100% (5641/5641), done.
$PATH interpreter not found in 
You may want to use the flags --with-lua, --with-lua-bin and/or --lua-suffix. See --help.

configure failed.

Makefile:2: config.unix: No such file or directory
make: *** No rule to make target `config.unix'.  Stop.
Makefile:2: config.unix: No such file or directory
make: *** No rule to make target `config.unix'.  Stop.
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
Finished. Use './launch' to start mattata. Be sure to set your bot token in configuration.example.lua, and then rename it to configuration.lua!

**Comment by joostlek** [comment]
Can you execute the script I sent and post that result here

On 8 Mar 2017 08:01, Samuelseggs <notifications@github.com> wrote:

still got error

Reading package lists... Done
W: Size of file /var/lib/apt/lists/toolbelt.heroku.com_ubuntu_._Packages.gz is not what the server reported 721 725
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'fortune-mod' instead of 'fortune'
E: Unable to locate package lua5.3
E: Couldn't find any package by regex 'lua5.3'
E: Unable to locate package liblua5.3-dev
E: Couldn't find any package by regex 'liblua5.3-dev'
Fetching: drydock-0.6.9.gem (100%)
Successfully installed drydock-0.6.9
Fetching: uri-redis-0.4.2.gem (100%)
Successfully installed uri-redis-0.4.2
Fetching: redis-3.3.3.gem (100%)
Successfully installed redis-3.3.3
Fetching: yajl-ruby-1.3.0.gem (100%)
Building native extensions. This could take a while...
Successfully installed yajl-ruby-1.3.0
Fetching: redis-dump-0.3.5.gem (100%)
Successfully installed redis-dump-0.3.5
5 gems installed
Cloning into 'luarocks'...
remote: Counting objects: 9643, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 9643 (delta 0), reused 0 (delta 0), pack-reused 9638
Receiving objects: 100% (9643/9643), 22.95 MiB | 14.25 MiB/s, done.
Resolving deltas: 100% (5641/5641), done.
$PATH interpreter not found in
You may want to use the flags --with-lua, --with-lua-bin and/or --lua-suffix. See --help.

configure failed.

Makefile:2: config.unix: No such file or directory
make: *** No rule to make target config.unix'. Stop. Makefile:2: config.unix: No such file or directory make: *** No rule to make targetconfig.unix'. Stop.
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
sudo: luarocks-5.3: command not found
Finished. Use './launch' to start mattata. Be sure to set your bot token in configuration.example.lua, and then rename it to configuration.lua!

**Comment by Samuelseggs** [comment]
samuelseggs:~/workspace/lua-5.3.4 $ sudo make install
cd src && mkdir -p /usr/local/bin /usr/local/include /usr/local/lib /usr/local/man/man1 /usr/local/share/lua/5.3 /usr/local/lib/lua/5.3
cd src && install -p -m 0755 lua luac /usr/local/bin
cd src && install -p -m 0644 lua.h luaconf.h lualib.h lauxlib.h lua.hpp /usr/local/include
cd src && install -p -m 0644 liblua.a /usr/local/lib
cd doc && install -p -m 0644 lua.1 luac.1 /usr/local/man/man1

**Comment by joostlek** [comment]
What does lua -v say?

**Comment by joostlek** [comment]
When you do lua -v what does it say?

On 8 Mar 2017 08:20, Samuelseggs <notifications@github.com> wrote:

samuelseggs:~/workspace/lua-5.3.4 $ sudo make install
cd src && mkdir -p /usr/local/bin /usr/local/include /usr/local/lib /usr/local/man/man1 /usr/local/share/lua/5.3 /usr/local/lib/lua/5.3
cd src && install -p -m 0755 lua luac /usr/local/bin
cd src && install -p -m 0644 lua.h luaconf.h lualib.h lauxlib.h lua.hpp /usr/local/include
cd src && install -p -m 0644 liblua.a /usr/local/lib
cd doc && install -p -m 0644 lua.1 luac.1 /usr/local/man/man1

**Comment by Samuelseggs** [comment]
Lua 5.3.4  Copyright (C) 1994-2017 Lua.org, PUC-Rio

**Comment by joostlek** [comment]
That's good, go on and edit the install.sh file, somewhere in the luarocks setup there's this:
./configure ............... -lua-suffix=5.3 
Remove that -lua-suffix=5.3

**Comment by Samuelseggs** [comment]
Error: Could not find header file for CURL
  No file curl/curl.h in /usr/local/include
  No file curl/curl.h in /usr/include

samuelseggs:~/workspace/mattata (master) $ ./launch.sh
./launch.sh: 7: ./launch.sh: lua5.3: not found
mattata has stopped!
./launch.sh: 7: ./launch.sh: lua5.3: not found
mattata has stopped!
./launch.sh: 7: ./launch.sh: lua5.3: not found
mattata has stopped!

**Comment by Samuelseggs** [comment]
Can i also leave this 

['log_chat'] = -1001053691206, -- This needs to be the numerical identifier of the chat you wish to log errors into. If it's not a private chat it should begin with a '-' symbol.

    ['log_admin_actions'] = true, -- If set to true, administrative actions will be logged in the configured channel (the numerical ID should be set as the value of log_channel).

    ['log_channel'] = -1001086181358, -- THe numerical ID of the chat to (if applicable) log administrative actions to.

    ['bug_reports_chat'] = -188808248, -- The numerical ID of the chat to send bug reports to.

    ['counter_channel'] = -1001081940117, -- The numerical ID of the channel to use in order for /counter to work.

**Comment by wrxck** [comment]
If you're still encountering these issues, please check out [the official mattata support group!](https://t.me/mattataSupport)

On a side note, if I recall correctly, cloud9 uses Ubuntu 14.04 and it's stated in the documentation that mattata has only been confirmed to work on Ubuntu 16.04 and later (it's a different story for other OSes, but that's irrelevant).
