### ISSUE TITLE
@mattatabot doesn't remove command(s) and reply

### ISSUE THREAD

**Issue by GitProfile** [wrxck/mattata#60]
![image](https://user-images.githubusercontent.com/33368293/32687146-e77a4488-c6c6-11e7-94d3-a421642bf208.png)
![image](https://user-images.githubusercontent.com/33368293/32687147-f07d50ca-c6c6-11e7-9635-3278f10cd38a.png)
![image](https://user-images.githubusercontent.com/33368293/32687156-27890078-c6c7-11e7-9466-43f85abd053b.png)

**Comment by GitProfile** [comment]
Why /voteban is work?
![image](https://user-images.githubusercontent.com/33368293/32687165-9a167436-c6c7-11e7-80a0-a2ab89ed2938.png)

**Comment by GitProfile** [comment]
Bot is stable?

**Comment by GitProfile** [comment]
Permissions:
![image](https://user-images.githubusercontent.com/33368293/32687172-d0f22248-c6c7-11e7-92a9-3e1e92f7b044.png)

**Comment by wrxck** [comment]
The first of these will be fixed in the next update, which I will release later today. The issue was a bug in `mattata.lua` which made all `update.message.is_natural_language` fields `true`, rather than `false` if it wasn't a natural language query.

As for the voteban plugin, could you please elaborate on what issue you're experiencing?
